import { ONCHAIN_DATA_ENTITY_SCHEMAS as CARDANO_ONCHAIN_DATA_ENTITY_SCHEMAS } from './cardano/entities.js';
import { ONCHAIN_DATA_ENTITY_SCHEMAS as EVM_ONCHAIN_DATA_ENTITY_SCHEMAS } from './evm/entities.js';

export const ONCHAIN_DATA_ENTITY_SCHEMAS = [...EVM_ONCHAIN_DATA_ENTITY_SCHEMAS, ...CARDANO_ONCHAIN_DATA_ENTITY_SCHEMAS];
