import { describe, expect, it } from 'vitest';
import { normalizeMilestoneToRecord } from '../../../../src/resources/milestones/normalize.js';
import { createMockMilestone } from '../../../utils/mock-helpers.js';

describe('Milestone Normalization', () => {
  describe('normalizeMilestoneToRecord', () => {
    it('should transform API response to DB record format', () => {
      const milestone = createMockMilestone({
        id: 1,
        proposal_id: 100,
        title: 'Test Milestone',
        status: 'in_progress',
        description: 'Test description',
        development_description: 'Test dev description',
        budget: 5000,
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-01-02T00:00:00Z',
      });

      const result = normalizeMilestoneToRecord(milestone);

      expect(result.proposalId).toBe(100);
      expect(result.title).toBe('Test Milestone');
      expect(result.status).toBe('in_progress');
      expect(result.description).toBe('Test description');
      expect(result.developmentDescription).toBe('Test dev description');
      expect(result.budget).toBe(5000);
      expect(result.createdAt).toBe('2024-01-01T00:00:00Z');
      expect(result.updatedAt).toBe('2024-01-02T00:00:00Z');
      expect(result.rawJson).toBe(JSON.stringify(milestone));
    });

    it('should not include id field (auto-generated by DB)', () => {
      const milestone = createMockMilestone();
      const result = normalizeMilestoneToRecord(milestone);

      expect(result).not.toHaveProperty('id');
    });

    it('should handle all milestone statuses', () => {
      const statuses = ['not_started', 'pending', 'in_progress', 'completed'] as const;

      for (const status of statuses) {
        const milestone = createMockMilestone({ status });
        const result = normalizeMilestoneToRecord(milestone);
        expect(result.status).toBe(status);
      }
    });

    it('should serialize raw JSON correctly', () => {
      const milestone = createMockMilestone({
        id: 42,
        proposal_id: 10,
        title: 'Complex Milestone',
      });

      const result = normalizeMilestoneToRecord(milestone);
      const parsed = JSON.parse(result.rawJson);

      expect(parsed.id).toBe(42);
      expect(parsed.proposal_id).toBe(10);
      expect(parsed.title).toBe('Complex Milestone');
    });
  });
});
