// This file is auto-generated - DO NOT EDIT MANUALLY
// Generated by: registry-generator.ts
// Last generated: 2025-10-21T14:16:59.772Z

export const REGISTRY_INDEX = {
  voting_engagement: ['1.0.0'],
} as const;

import _voting_engagement_1_0_0 from './voting_engagement/1.0.0.json' with { type: 'json' };

export const _DEFINITIONS: Record<string, unknown> = {
  'voting_engagement@1.0.0': _voting_engagement_1_0_0 as unknown,
} as const;
