import { describe, expect, it } from 'vitest';
import { normalizeReviewToRecord } from '../../../../src/resources/reviews/normalize.js';
import { createMockReview } from '../../../utils/mock-helpers.js';

describe('Review Normalization', () => {
  describe('normalizeReviewToRecord', () => {
    it('should transform API response to DB record format', () => {
      const review = createMockReview({
        proposal_id: 1,
        reviewer_id: 10,
        review_type: 'expert',
        overall_rating: 'good',
        feasibility_rating: 'high',
        viability_rating: 'medium',
        desirability_rating: 'high',
        usefulness_rating: 'high',
        created_at: '2024-01-01T00:00:00Z',
      });

      const result = normalizeReviewToRecord(review);

      expect(result.proposalId).toBe(1);
      expect(result.reviewerId).toBe(10);
      expect(result.reviewType).toBe('expert');
      expect(result.overallRating).toBe('good');
      expect(result.feasibilityRating).toBe('high');
      expect(result.viabilityRating).toBe('medium');
      expect(result.desirabilityRating).toBe('high');
      expect(result.usefulnessRating).toBe('high');
      expect(result.createdAt).toBe('2024-01-01T00:00:00Z');
      expect(result.rawJson).toBe(JSON.stringify(review));
    });

    it('should not include reviewId field (auto-generated by DB)', () => {
      const review = createMockReview();
      const result = normalizeReviewToRecord(review);

      expect(result).not.toHaveProperty('reviewId');
    });

    it('should handle null proposal_id', () => {
      const review = createMockReview({
        proposal_id: undefined,
      });

      const result = normalizeReviewToRecord(review);
      expect(result.proposalId).toBeNull();
    });

    it('should handle null reviewer_id', () => {
      const review = createMockReview({
        reviewer_id: undefined,
      });

      const result = normalizeReviewToRecord(review);
      expect(result.reviewerId).toBeNull();
    });

    it('should handle null created_at', () => {
      const review = createMockReview({
        created_at: undefined,
      });

      const result = normalizeReviewToRecord(review);
      expect(result.createdAt).toBeNull();
    });

    it('should serialize raw JSON correctly', () => {
      const review = createMockReview({
        proposal_id: 42,
        review_type: 'community',
      });

      const result = normalizeReviewToRecord(review);
      const parsed = JSON.parse(result.rawJson);

      expect(parsed.proposal_id).toBe(42);
      expect(parsed.review_type).toBe('community');
    });
  });
});
