networks:
    production:
        external: true

x-workflows-secret-environment: &workflows-secret-environment
    MONGODB_USER: "${MONGODB_USER:?missing MONGODB_USER}"
    MONGODB_PASSWORD: "${MONGODB_PASSWORD:?missing MONGODB_PASSWORD}"
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:?missing AWS_ACCESS_KEY_ID}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:?missing AWS_SECRET_ACCESS_KEY}"
    DEEPFUNDING_API_KEY: "${DEEPFUNDING_API_KEY:?missing DEEPFUNDING_API_KEY}"
    ALCHEMY_API_KEY: "${ALCHEMY_API_KEY:?missing ALCHEMY_API_KEY}"
    BLOCKFROST_API_KEY: "${BLOCKFROST_API_KEY:?missing BLOCKFROST_API_KEY}"
    ONCHAIN_DATA_POSTGRES_USER: "${ONCHAIN_DATA_POSTGRES_USER:?missing ONCHAIN_DATA_POSTGRES_USER}"
    ONCHAIN_DATA_POSTGRES_PASSWORD: "${ONCHAIN_DATA_POSTGRES_PASSWORD:?missing ONCHAIN_DATA_POSTGRES_PASSWORD}"

services:
    ui:
        container_name: ui
        image: ghcr.io/reputo-org/reputo/ui:${IMAGE_TAG}
        restart: unless-stopped
        networks: [production]
        env_file:
            - ../env/ui.env
        labels:
            - traefik.enable=true
            - traefik.http.routers.ui.rule=Host(`${UI_DOMAIN}`)
            - traefik.http.routers.ui.priority=1
            - traefik.http.routers.ui.tls=true
            - traefik.http.routers.ui.tls.certresolver=cloudflare
            - traefik.http.routers.ui.entrypoints=websecure
            - traefik.http.services.ui.loadbalancer.server.port=8080
            - com.centurylinklabs.watchtower.enable=true

    api:
        container_name: api
        image: ghcr.io/reputo-org/reputo/api:${IMAGE_TAG}
        restart: unless-stopped
        networks: [production]
        labels:
            - traefik.enable=true
            - traefik.http.routers.api.rule=Host(`${API_DOMAIN}`)
            - traefik.http.routers.api.tls=true
            - traefik.http.routers.api.tls.certresolver=cloudflare
            - traefik.http.routers.api.entrypoints=websecure
            - traefik.http.routers.api.middlewares=api-cors
            - traefik.http.routers.api-ui.rule=Host(`${UI_DOMAIN}`) && PathPrefix(`/api`)
            - traefik.http.routers.api-ui.priority=100
            - traefik.http.routers.api-ui.tls=true
            - traefik.http.routers.api-ui.tls.certresolver=cloudflare
            - traefik.http.routers.api-ui.entrypoints=websecure
            - traefik.http.routers.api-ui.middlewares=api-cors
            - traefik.http.routers.api-ui.service=api
            - traefik.http.services.api.loadbalancer.server.port=3000
            - traefik.http.middlewares.api-cors.headers.accessControlAllowMethods=GET,OPTIONS,PUT,POST,DELETE,PATCH
            - traefik.http.middlewares.api-cors.headers.accessControlAllowOriginList=${ALLOWED_ORIGINS:-*}
            - traefik.http.middlewares.api-cors.headers.accessControlAllowHeaders=Content-Type,Authorization,Accept,Origin,X-Requested-With
            - traefik.http.middlewares.api-cors.headers.accessControlMaxAge=3600
            - com.centurylinklabs.watchtower.enable=true
        env_file:
            - ../env/api.env
        environment:
            MONGODB_USER: "${MONGODB_USER:?missing MONGODB_USER}"
            MONGODB_PASSWORD: "${MONGODB_PASSWORD:?missing MONGODB_PASSWORD}"
            AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:?missing AWS_ACCESS_KEY_ID}"
            AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:?missing AWS_SECRET_ACCESS_KEY}"
            DEEP_ID_CLIENT_SECRET: "${DEEP_ID_CLIENT_SECRET:?missing DEEP_ID_CLIENT_SECRET}"
            AUTH_TOKEN_ENCRYPTION_KEY: "${AUTH_TOKEN_ENCRYPTION_KEY:?missing AUTH_TOKEN_ENCRYPTION_KEY}"

    orchestrator-worker:
        container_name: orchestrator-worker
        image: ghcr.io/reputo-org/reputo/workflows:${IMAGE_TAG}
        command: ['pnpm', 'start:orchestrator']
        restart: unless-stopped
        networks: [production]
        env_file:
            - ../env/workflows.env
        environment: *workflows-secret-environment
        labels:
            - com.centurylinklabs.watchtower.enable=true

    onchain-data-worker:
        container_name: onchain-data-worker
        image: ghcr.io/reputo-org/reputo/workflows:${IMAGE_TAG}
        command: ['pnpm', 'start:onchain-data']
        restart: unless-stopped
        networks: [production]
        env_file:
            - ../env/workflows.env
        environment: *workflows-secret-environment
        labels:
            - com.centurylinklabs.watchtower.enable=true

    typescript-worker:
        container_name: typescript-worker
        image: ghcr.io/reputo-org/reputo/workflows:${IMAGE_TAG}
        command: ['pnpm', 'start:algorithm-typescript']
        restart: unless-stopped
        networks: [production]
        env_file:
            - ../env/workflows.env
        environment: *workflows-secret-environment
        labels:
            - com.centurylinklabs.watchtower.enable=true
