[[user_group]]
name = "admins"
everyone = false
users = []
all.Server = "Write"
all.Stack = "Write"
all.Procedure = "Write"
all.Alerter = "Write"
all.ResourceSync = "Write"
permissions = []

[[user_group]]
name = "engineers"
everyone = false
users = []
permissions = [
  { target.type = "Server", target.id = "staging", level = "Read" },
  { target.type = "Stack", target.id = "reputo-apps-staging", level = "Execute" },
  { target.type = "Stack", target.id = "reputo-infra-staging", level = "Execute" },
  { target.type = "Server", target.id = "production", level = "Read" },
  { target.type = "Stack", target.id = "reputo-apps-production", level = "Read" },
  { target.type = "Stack", target.id = "reputo-infra-production", level = "Read" },
  { target.type = "Procedure", target.id = "promote-production", level = "Read" },
]

[[user_group]]
name = "release-managers"
everyone = false
users = []
permissions = [
  { target.type = "Server", target.id = "production", level = "Read" },
  { target.type = "Stack", target.id = "reputo-apps-production", level = "Read" },
  { target.type = "Procedure", target.id = "promote-production", level = "Execute" },
]
