name: main 🚢
run-name: main 🚢

on:
    push:
        branches: [main]

concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true

jobs:
    quality-gate:
        uses: ./.github/workflows/_quality-gate.yml
        secrets: inherit

    build-and-push:
        needs: quality-gate
        uses: ./.github/workflows/_build-and-push.yml
        with:
            ref: ${{ github.sha }}
            push: true
            affected: true
            base-ref: ${{ github.event.before }}
            tags: |
                type=raw,value=staging

    release:
        needs: build-and-push
        uses: ./.github/workflows/release.yml
        secrets: inherit

    wait-for-watchtower:
        name: wait-for-watchtower
        needs: build-and-push
        if: ${{ needs.build-and-push.outputs.affected-count != '0' }}
        runs-on: ubuntu-22.04
        environment:
            name: staging
            url: https://staging.logid.xyz
        steps:
            - name: Wait for Watchtower to pull the new image
              run: sleep 90
            - name: '✅ Deployment should now be live'
              run: |
                  echo "✅ Your app should be up at ${{ job.environment.url }}"
