name: Pull Preview 👀
run-name: Pull Preview 👀
on:
    pull_request:
        branches: [main]
        types: [labeled, unlabeled, synchronize, closed, reopened]

concurrency: ${{ github.ref }}

jobs:
    build:
        if: |
            github.event.action != 'closed' &&
            (github.event.label.name == 'pullpreview' || contains(github.event.pull_request.labels.*.name, 'pullpreview'))
        uses: ./.github/workflows/_build-and-push.yml
        with:
            ref: ${{ github.event.pull_request.head.sha }}
            push: true
            tags: |
                type=raw,value=preview-${{ github.event.pull_request.head.sha }}

    deploy:
        name: deploy
        needs: build
        if: |
            !failure() && !cancelled() &&
            (github.event.label.name == 'pullpreview' || contains(github.event.pull_request.labels.*.name, 'pullpreview'))
        runs-on: ubuntu-latest
        timeout-minutes: 30
        permissions:
            contents: read
            deployments: write
            pull-requests: write
            statuses: write
        steps:
            - uses: actions/checkout@v4

            - name: Generate .env 
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  DEEPFUNDING_API_KEY: ${{ secrets.DEEPFUNDING_API_KEY }}
              run: |
                    cat > docker/preview/.env <<EOF
                    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
                    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
                    DEEPFUNDING_API_KEY=$DEEPFUNDING_API_KEY
                    PREVIEW_IMAGE_TAG=sha-${{ github.event.pull_request.head.sha }}
                    EOF

            - name: Generate MongoDB keyfile
              run: |
                  openssl rand -base64 768 > docker/mongo/keyfile.txt
                  chmod 400 docker/mongo/keyfile.txt

            - uses: pullpreview/action@v6
              with:
                  label: pullpreview
                  provider: lightsail
                  instance_type: large
                  compose_files: docker/preview/docker-compose.preview.yml
                  compose_options: ''
                  ttl: 48h
              env:
                  AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
                  AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
                  AWS_REGION: 'eu-central-1'
